# Generated by Django 4.0 on 2022-11-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
