# Generated by Django 4.0 on 2022-11-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_usermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
