# Generated by Django 4.0 on 2022-11-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
